# Generated by Codex on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_event_id", models.CharField(max_length=64, unique=True)),
                ("event_index", models.PositiveIntegerField(default=0)),
                ("period", models.PositiveIntegerField(default=1)),
                ("possession", models.PositiveIntegerField(default=0)),
                ("minute", models.PositiveIntegerField()),
                ("second", models.PositiveIntegerField(default=0)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("end_x", models.FloatField()),
                ("end_y", models.FloatField()),
                ("length", models.FloatField(blank=True, null=True)),
                ("angle", models.FloatField(blank=True, null=True)),
                ("outcome", models.CharField(choices=[("complete", "Complete"), ("incomplete", "Incomplete"), ("out", "Out"), ("offside", "Offside"), ("unknown", "Unknown")], default="complete", max_length=20)),
                ("height", models.CharField(choices=[("ground", "Ground"), ("low", "Low"), ("high", "High"), ("unknown", "Unknown")], default="ground", max_length=20)),
                ("body_part", models.CharField(blank=True, choices=[("right_foot", "Right Foot"), ("left_foot", "Left Foot"), ("head", "Head"), ("chest", "Chest"), ("other", "Other")], max_length=20)),
                ("technique", models.CharField(blank=True, choices=[("normal", "Normal"), ("half_volley", "Half Volley"), ("volley", "Volley"), ("lob", "Lob"), ("backheel", "Backheel"), ("overhead", "Overhead"), ("unknown", "Unknown")], max_length=20)),
                ("pass_type", models.CharField(choices=[("open_play", "Open Play"), ("free_kick", "Free Kick"), ("corner", "Corner"), ("goal_kick", "Goal Kick"), ("throw_in", "Throw In"), ("kick_off", "Kick Off"), ("recovery", "Recovery"), ("unknown", "Unknown")], default="open_play", max_length=20)),
                ("play_pattern", models.CharField(blank=True, max_length=50)),
                ("assisted_shot_event_id", models.CharField(blank=True, max_length=64)),
                ("under_pressure", models.BooleanField(default=False)),
                ("is_cross", models.BooleanField(default=False)),
                ("is_cut_back", models.BooleanField(default=False)),
                ("is_switch", models.BooleanField(default=False)),
                ("is_through_ball", models.BooleanField(default=False)),
                ("shot_assist", models.BooleanField(default=False)),
                ("goal_assist", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="passes", to="core.match")),
                ("player", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="passes", to="core.player")),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="received_passes", to="core.player")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="passes", to="core.team")),
            ],
            options={
                "ordering": ["minute", "second", "id"],
                "indexes": [
                    models.Index(fields=["match"], name="core_pass_match_i_eb66d7_idx"),
                    models.Index(fields=["team"], name="core_pass_team_id_7907e3_idx"),
                    models.Index(fields=["player"], name="core_pass_player__e88f4e_idx"),
                    models.Index(fields=["recipient"], name="core_pass_recipie_92eebf_idx"),
                    models.Index(fields=["possession"], name="core_pass_possess_6a2cdd_idx"),
                    models.Index(fields=["event_index"], name="core_pass_event_i_3850fe_idx"),
                    models.Index(fields=["minute", "second"], name="core_pass_minute__eced40_idx"),
                    models.Index(fields=["outcome"], name="core_pass_outcome_0ed7a6_idx"),
                    models.Index(fields=["pass_type"], name="core_pass_pass_ty_d2c322_idx"),
                    models.Index(fields=["shot_assist"], name="core_pass_shot_as_720eb8_idx"),
                    models.Index(fields=["goal_assist"], name="core_pass_goal_as_3a8398_idx"),
                ],
            },
        ),
    ]
