# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchteamstats",
            name="completed_passes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchteamstats",
            name="pass_accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="matchteamstats",
            name="passes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="matchteamstats",
            name="possession_seconds",
            field=models.FloatField(default=0.0),
        ),
    ]
