# Generated by Django 6.0.1 on 2026-04-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_live_match_stats_counters'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchstate',
            name='core_matchs_status_8dba4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchstate',
            name='core_matchs_last_ev_6c5639_idx',
        ),
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='current_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matchteamstats',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_states', to='core.event'),
        ),
        migrations.AddField(
            model_name='matchteamstats',
            name='possession',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MatchState',
        ),
    ]
