# Generated by Django 6.0.2 on 2026-03-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pass'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_match_i_ae4a12_idx',
            old_name='core_pass_match_i_eb66d7_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_team_id_cccbce_idx',
            old_name='core_pass_team_id_7907e3_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_player__853f5f_idx',
            old_name='core_pass_player__e88f4e_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_recipie_9fd07b_idx',
            old_name='core_pass_recipie_92eebf_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_possess_4036d7_idx',
            old_name='core_pass_possess_6a2cdd_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_event_i_4ed52c_idx',
            old_name='core_pass_event_i_3850fe_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_minute_7b70b0_idx',
            old_name='core_pass_minute__eced40_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_outcome_1e69c3_idx',
            old_name='core_pass_outcome_0ed7a6_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_pass_ty_b973da_idx',
            old_name='core_pass_pass_ty_d2c322_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_shot_as_806c74_idx',
            old_name='core_pass_shot_as_720eb8_idx',
        ),
        migrations.RenameIndex(
            model_name='pass',
            new_name='core_pass_goal_as_c984db_idx',
            old_name='core_pass_goal_as_3a8398_idx',
        ),
    ]
