# Generated by Django 6.0.1 on 2026-03-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manual_entry_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
