# Generated by Django 6.0.1 on 2026-03-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_competition_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='is_league',
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('league', 'League'), ('cup', 'Cup'), ('friendly', 'Friendly')], default='league', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='match_uid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type'], name='core_match_match_t_e5a35b_idx'),
        ),
    ]
