# Generated by Django 6.0.1 on 2026-03-18 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_season_is_league_match_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stadium'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
