# Generated by Django 6.0.1 on 2026-03-18 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_match_stadium_stadium_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_match_t_e5a35b_idx',
        ),
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.stadium'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_date'], name='core_match_match_d_91573d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'match_date'], name='core_match_season__c892b8_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['stadium'], name='core_match_stadium_fb3630_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='home_away_not_same'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_uid',
        ),
    ]
