# Generated by Django 6.0.1 on 2026-03-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_match_core_match_match_t_e5a35b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
