# Generated by Django 6.0.2 on 2026-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_match_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
