# Generated by Django 6.0.1 on 2026-03-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_competition_country_alter_stadium_country_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='home_away_not_same',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competition',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='period',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='outcome',
            field=models.CharField(choices=[('goal', 'Goal'), ('saved', 'Saved'), ('saved_off_target', 'Saved Off Target'), ('blocked', 'Blocked'), ('off_target', 'Off Target'), ('wayward', 'Wayward'), ('post', 'Post')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team__lt', models.F('away_team'))), name='home_team_not_equal_away_team'),
        ),
    ]
