# Generated by Django 6.0.1 on 2026-03-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_match_home_away_not_same_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='home_team_not_equal_away_team',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='home_team_not_equal_away_team'),
        ),
    ]
