# Generated by Django 6.0.1 on 2026-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_match_home_team_not_equal_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
