# Generated by Django 6.0.1 on 2026-03-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_match_match_week_match_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='assist_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_shots', to='core.player'),
        ),
        migrations.AddField(
            model_name='shot',
            name='assist_type',
            field=models.CharField(blank=True, choices=[('cross', 'Cross'), ('through_ball', 'Through Ball'), ('cutback', 'Cutback'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='shot',
            name='defenders_in_between',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='gk_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='is_big_chance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shot',
            name='play_pattern',
            field=models.CharField(blank=True, choices=[('open_play', 'Open Play'), ('corner', 'Corner'), ('free_kick', 'Free Kick'), ('penalty', 'Penalty')], max_length=20),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_angle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shot',
            name='under_pressure',
            field=models.BooleanField(default=False),
        ),
    ]
