# Generated by Django 6.0.1 on 2026-03-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shot_assist_player_shot_assist_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
