# Generated by Django 6.0.1 on 2026-03-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_season_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
    ]
