# Generated by Django 6.0.1 on 2026-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_match_match_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='stage',
            new_name='stage_name',
        ),
        migrations.AddField(
            model_name='match',
            name='stage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamstats',
            name='penalties',
            field=models.IntegerField(default=0),
        ),
    ]
