# Generated by Django 6.0.1 on 2026-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_substitution_table_alignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_match_i_40ee3c_idx',
            old_name='core_event_match_i_2a7f2f_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_match_i_cd604c_idx',
            old_name='core_event_match_i_36adca_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_minute_f9147b_idx',
            old_name='core_event_minute__7ac85c_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_period_9e356a_idx',
            old_name='core_event_period_0ee0e2_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_type_a3ce08_idx',
            old_name='core_event_type_b221e4_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_team_id_8bcffb_idx',
            old_name='core_event_team_id_f3f48c_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_player__eaf22f_idx',
            old_name='core_event_player__33957a_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_possess_b1d10b_idx',
            old_name='core_event_possess_054ca1_idx',
        ),
        migrations.RenameIndex(
            model_name='substitution',
            new_name='core_substi_match_i_e0389a_idx',
            old_name='core_substi_match_i_6cafcb_idx',
        ),
        migrations.RenameIndex(
            model_name='substitution',
            new_name='core_substi_team_id_811a7e_idx',
            old_name='core_substi_team_id_353dc7_idx',
        ),
        migrations.RenameIndex(
            model_name='substitution',
            new_name='core_substi_player__c19c72_idx',
            old_name='core_substi_player__fb0f44_idx',
        ),
        migrations.RenameIndex(
            model_name='substitution',
            new_name='core_substi_player__f60fd0_idx',
            old_name='core_substi_player__3e620f_idx',
        ),
        migrations.RenameIndex(
            model_name='substitution',
            new_name='core_substi_period_e405e6_idx',
            old_name='core_substi_period_250b15_idx',
        ),
        migrations.RenameIndex(
            model_name='substitution',
            new_name='core_substi_minute_6ce677_idx',
            old_name='core_substi_minute__732bd1_idx',
        ),
        migrations.AlterField(
            model_name='shot',
            name='body_part',
            field=models.CharField(blank=True, choices=[('right_foot', 'Right Foot'), ('left_foot', 'Left Foot'), ('head', 'Head'), ('other', 'Other')], max_length=20),
        ),
    ]
