# Generated by Django 6.0.2 on 2026-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_league',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, upload_to='competition/logos'),
        ),
    ]
