# Generated by Django 6.0.1 on 2026-03-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0002_season_is_league_season_slug_alter_competition_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_league',
            field=models.BooleanField(default=True),
        ),
    ]
