# Generated by Django 6.0.2 on 2026-02-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0003_match_away_shots_match_away_shots_on_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='body_part',
            field=models.CharField(blank=True, choices=[('right_foot', 'Right Foot'), ('left_foot', 'Left Foot'), ('head', 'Head')], max_length=20),
        ),
        migrations.AddField(
            model_name='shot',
            name='is_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('open_play', 'Open Play'), ('penalty', 'Penalty'), ('free_kick', 'Free Kick')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shot',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='futball.match'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='outcome',
            field=models.CharField(choices=[('goal', 'Goal'), ('saved', 'Saved'), ('blocked', 'Blocked'), ('off_target', 'Off Target')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='futball.team'),
        ),
    ]
