# Generated by Django 6.0.1 on 2026-03-09 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0004_competitionformat_alter_competition_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='futball.competitionformat'),
        ),
    ]
