# Generated by Django 6.0.1 on 2026-02-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0005_news_competition_created_at_competition_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xg', models.FloatField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.ImageField(upload_to='news/content/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date']},
        ),
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['minute', 'second']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_shots',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_shots_on_target',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_shots',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_shots_on_target',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('finished', 'Finished'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(upload_to='news/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('competition', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'country')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season'], name='futball_mat_season__4cd259_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team'], name='futball_mat_home_te_2696cf_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team'], name='futball_mat_away_te_3b5c98_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='futball_mat_status_b0824c_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['match'], name='futball_sho_match_i_1e55df_idx'),
        ),
        migrations.AddIndex(
            model_name='shot',
            index=models.Index(fields=['team'], name='futball_sho_team_id_3d22bb_idx'),
        ),
        migrations.AddField(
            model_name='matchteamstats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='futball.match'),
        ),
        migrations.AddField(
            model_name='matchteamstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futball.team'),
        ),
        migrations.AlterUniqueTogether(
            name='matchteamstats',
            unique_together={('match', 'team')},
        ),
    ]
