# Generated by Django 6.0.1 on 2026-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0005_alter_competition_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('live', 'Live'), ('paused', 'Paused')], default='scheduled', max_length=20),
        ),
        migrations.DeleteModel(
            name='MatchEvent',
        ),
    ]
