# Generated by Django 6.0.1 on 2026-02-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("futball", "0006_matchteamstats_newscontentimage_alter_match_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("home_goals", models.IntegerField(default=0)),
                ("away_goals", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("match", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="score", to="futball.match")),
            ],
        ),
    ]
