# Generated by Django 6.0.1 on 2026-02-07 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0007_matchscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futball.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=False)),
                ('minute_on', models.IntegerField(default=0)),
                ('minute_off', models.IntegerField(default=90)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futball.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futball.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futball.team')),
            ],
            options={
                'unique_together': {('player', 'match')},
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsContentImage',
        ),
        migrations.AddField(
            model_name='shot',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futball.player'),
        ),
    ]
