"""Database migration module: 0009_playermatch_created_at_playermatch_updated_at_and_more."""

# Generated by Django 6.0.1 on 2026-02-09 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0008_player_playermatch_delete_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MatchScore',
        ),
    ]
