# Generated by Django 6.0.2 on 2026-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0008_shot_external_event_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsContentImage',
        ),
        migrations.AddField(
            model_name='news',
            name='hot_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='matchteamstats',
            index=models.Index(fields=['match'], name='futball_mat_match_i_de492b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchteamstats',
            index=models.Index(fields=['team'], name='futball_mat_team_id_9fd428_idx'),
        ),
    ]
