# Generated by Django 6.0.1 on 2026-02-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0009_playermatch_created_at_playermatch_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamstats',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
