"""Database migration module: 0011_news_newscontentimage_team_logo."""

# Generated by Django 6.0.1 on 2026-02-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0010_matchteamstats_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=155)),
                ('shortdesc', models.CharField(max_length=155)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='news/thumbnail/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.ImageField(upload_to='news/content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team/logos/'),
        ),
    ]
