# Generated by Django 6.0.1 on 2026-01-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
