# Generated by Django 6.0.1 on 2026-01-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_shots_on_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_shots_on_target',
            field=models.IntegerField(default=0),
        ),
    ]
